# Note: AI generated
name: Build and Minify

on:
  push:
    branches:
      - main
      - release-branch
  pull_request:
    branches:
      - main
      - release-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build the project
        run: node ./scripts/build.swc.mjs
        env:
          NODE_ENV: production
          RELEASE_BRANCH: ${{ github.ref_name }}
          BUILD_MINIFY: true
          DEV: false

      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            dist/neocord.js
            dist/neocord.min.js
